language: python

python:
  - 2.7
 

before_install:
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++


install:
  - npm install canvas vega vega-lite
  

script:
  - vl2vg  test.json
  - vl2png test.json > test.png
  - vl2svg test.json > test.eps